[pytest]
# pytest for backend tests
pythonpath = .

# format for test files
python_files = test_*.py

# tests are at /tests
testpaths = ../tests

minversion = 7.0

# test markers
markers =
    unit: Unit tests
    integration: Integration tests

# output with options
# verbose, prints name and result of test
# only uses markets in file
# shows short error msgs instead of full stack trace
# prints recap with skipped, failed, error, passed tests.

addopts = 
    -v
    --strict-markers
    --tb=short
    --disable-warnings
    -ra
    --cov=app
    --cov-report=term-missing

# disabling printing logs to terminal during tests and logs all at info level or higher print. (no debug)
log_cli = false
log_cli_level = INFO